config/routes.rb
MySite::Application.routes.draw do

  root "pages#index"
  get "/home" => "pages#index", as: "about"
  get "/okgamer" => "pages#okgamer", as: "okgamer"
  get "/resume" => "pages#resume", as: "resume"

  

end

app/models/pages.rb
class Pages < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

	def okgamer
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Mike's Website" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Nav Bar -->
 
    <div class="row">
      <div class="large-12 columns">
        <div class="nav-bar right">
         <ul class="button-group">
           <li><%= link_to "Current Project", okgamer_path, :class => "button" %></li>
           <li><%= link_to "Resume", resume_path, :class => "button" %></li>
          </ul>
        </div>
        <h1><small><%= link_to "Michael James Cooley", about_path %></small></h1>
        <hr />
      </div>
    </div>
   
    <!-- End Nav -->

    <%= yield %>

    <!-- Footer -->
 
    <footer class="row">
      <div class="large-12 columns">
        <hr />
        <div class="row">
          <div class="large-6 columns">
            <p><%= mail_to "mikejames386@gmail.com", "Shoot me an email" %></p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><a href="https://github.com/mikejames386"><i class="fa fa-github"></i></a></li>
              <li><a href="https://twitter.com/maladaptedmike"><i class="fa fa-twitter"></i></a></li>
              <li><a href="http://www.linkedin.com/pub/michael-cooley/48/426/337/"><i class="fa fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/index.html.erb
  <!-- Main Page Content and Sidebar -->
 
  <div class="row">
 
    <!-- Main Content -->
    <div class="large-12 columns" role="content">
 
      <article>
 
        <h3>Who Am I?</h3> 
        <div class="row">
          <div class="large-8 columns">
            <p>I am a web developer, music fan, beer aficionado and Mario Kart champion.  Welcome to my website.  As a recent graduate of MakerSquare (an intensive, full-time web development bootcamp), I am excited and ready to work on projects as a junior developer.</p>
            <p>I have experience building applications using HTML/CSS, Javascript and Ruby on Rails.  Although Ruby is my true love when it comes to coding, I have recently started learning and working with the AngularJS framework and I am very excited about the possibilities.</p>
            <p>I am currently a contributor to <%= link_to "OkGamer", "https://okgamer.herokuapp.com/" %>. OkGamer is an application that I started as a student at MakerSquare.  The goal of OkGamer is to improve the quality of interactions in online multiplayer video games by matching players with other people who have similar gaming interests and styles.</p>
          </div>
          <div class="large-4 columns">
            <img src="https://scontent-a-ord.xx.fbcdn.net/hphotos-ash3/375643_10151364619500736_1766570733_n.jpg" />
          </div>
        </div>
 
      </article>
 
    </div>
 
    <!-- End Main Content -->
 
 
    
  </div>
 
  <!-- End Main Content and Sidebar -->
 
 
  

app/views/pages/okgamer.html.erb
	
	<div class="row">
		<div class="large-12 columns" role="content">
			<div>
				<article>
					<h3>What is <%= link_to "OkGamer?", "https://okgamer.herokuapp.com/" %></h3>
					<p>OkGamer is designed to connect players on online multiplayer games like Grand Theft Auto V with other games that share their gaming personality.  It began as a final project at MakerSquare that two other developers and myself built in Ruby on Rails over the course of three weeks.</p>
				</article>
			</div>
		</div>
   	<div class="large-12 columns">
    <div id="slider">
    	<ul data-orbit>
			  <li>
			    <%= image_tag("http://i.imgur.com/gK6uUSu.jpg") %>
			    <div class="orbit-caption">This is the splash page that a user sees before they log in</div>
			  </li>
			  <li>
			    <%= image_tag("http://i.imgur.com/zXLiGIH.jpg") %>
			    <div class="orbit-caption">After a user signs up they give their Xbox Live Gamertag and answer a short quiz</div>
			  </li>
			  <li>
			    <%= image_tag("http://i.imgur.com/xjXJndI.jpg") %>
			    <div class="orbit-caption">At which point they are matched with other users based on their answers to the above quiz</div>
			  </li>
			  <li>
			    <%= image_tag("http://i.imgur.com/oYxn3r9.jpg") %>
			    <div class="orbit-caption">A user can then send a message to his or her matches to set up team formation</div>
			  </li>
			</ul>
    </div>

    <hr />
    </div>
  </div>
  

app/views/pages/resume.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Michael James Cooley</h1>
		<p class="something">4700 west guadalupe street, austin</p>
		<p class="something">mikejames386@gmail.com | 614.551.2644</p>
	</div>
	<div class="large-12 columns resume">
		<h2>RELEVANT EXPERIENCE</h2>
		<p class="something">Student Web Developer <span class="connector_text">at</span> MakerSquare <span class="connector_text">from</span> 07.2013 <span class="connector_text">to</span> 09.2013</p>
		<p>Learned to develop web applications using Ruby on Rails, JavaScript and .js frameworks like jQuery, Underscore and Backbone, and HTML/CSS. Learned good development practices such as writing good code, paired programming and version management with GitHub. Deployed apps to Heroku. Examples of the types of projects I worked on:<br/>
			<span class="something">OkGamer</span> is a matchmaking app for online multiplayer gamers built in Ruby on Rails. It uses the Xbox API, Devise for user authentication and the Mailboxer gem for messaging.<br/>
			<span class="something">SocialOne</span> is a platform that posts to Twitter and Facebook. My first project using APIs.</p>
	</div>
	<div class="large-12 columns resume">
		<h2>EMPLOYMENT HISTORY</h2>
		<p class="something">Graduate Research Assistant <span class="connector_text">at</span> Seton Hall University <span class="connector_text">from</span> 2009 <span class="connector_text">to</span> 2011</p>
		<p>Covered lectures, maintained regular office hours and provided tutoring for Undergraduate Intro- duction to Psychology course. Designed and conducted neuropsychological research.</p>
		<p class="something">Archaeological Field Technician <span class="connector_text">at</span> Various <span class="connector_text">from</span> 2007 <span class="connector_text">to</span> 2008</p>
		<p>Conducted excavations and field surveys. Identified, collected and cataloged cultural artifacts.</p>
		<p class="something">Undergraduate Research Assistant <span class="connector_text">at</span> Northeast Ohio University <span class="connector_text">from</span> 2004 <span class="connector_text">to</span> 2006</p>
		<p>Assisted professor with research in rodent joint development. Conducted dissections of mice. Recorded data and used SPSS and Systat for analysis.</p>
	</div>
	<div class="large-12 columns resume">
		<div>
			<h2>EDUCATION</h2>
			<div>
				<p class="something">graduate student <span class="connector_text">at</span> Seton Hall University <span class="connector_text">from</span> 2009 <span class="connector_text">to</span> 2011</p>
				<p>studied Experimental Psychology</p>
			</div>
			<div>
				<p class="something">student <span class="connector_text">at</span> Wright State University <span class="connector_text">in</span> 2009</p>
				<p>earned Bachelor of Science in Psychology in 2009</p>
			</div>
			<div>
				<p class="something">student <span class="connector_text">at</span> Kent State University <span class="connector_text">from</span> 2002 <span class="connector_text">to</span> 2007</p>		
				<p>earned Bachelor of Science in Biological Anthropology in 2007</p>
			</div>
		<div>
	</div>
	<div class="large-12 columns resume">
		<div>
			<h2>Technology</h2>
			<div class="large-3 columns">
				<p class="something"><span class="connector_text">Ruby</span></p>
				<p>Ruby on Rails</p>
			</div>
			<div class="large-3 columns">
				<p class="something"><span class="connector_text">Javascript</span></p>
				<p class="something"><span class="connector_text">Underscore.js</span></p>
				<p>jQuery</p>
			</div>
			<div class="large-3 columns">
				<p class="something"><span class="connector_text">Backbone.js</span></p>
				<p class="something"><span class="connector_text">HTML/CSS</span></p>
				<p>SPSS</p>
			</div>
			<div class="large-3 columns">
				<p class="something"><span class="connector_text">Github</span></p>
				<p>Heroku</p>
			</div>
		</div>
	</div>

</div>